name = "Create"
author = "Ruzgarr"
version = "0.9.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "206404f0d41c32a1a9e572b766f193dd341f87cfe376491d618cc088aa0c6101"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
