name = "Create"
author = "Ruzgarr"
version = "0.9.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85447af430b06ccbe8717c634f2f1674c92bcb834cc7982ca7c3235e954fb2b3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
